"""ajoute associations professeur matieres et promotions

Revision ID: 2ff4b3274644
Revises: 012ae6c1598e
Create Date: 2026-07-13 22:06:02.956030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff4b3274644'
down_revision = '012ae6c1598e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professeur_matieres',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id', 'matiere_id')
    )
    op.create_table('professeur_promotions',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id', 'promotion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professeur_promotions')
    op.drop_table('professeur_matieres')
    # ### end Alembic commands ###
