"""etat initial fusionne (version2)

Revision ID: ce09f258c38a
Revises: 
Create Date: 2026-07-12 11:25:34.202879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce09f258c38a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_etablissement', sa.String(length=150), nullable=False),
    sa.Column('seuil_absences', sa.Integer(), nullable=False),
    sa.Column('tolerance_retard_minutes_defaut', sa.Integer(), nullable=False),
    sa.Column('contact_support_email', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('batiment', sa.String(length=50), nullable=True),
    sa.Column('qr_code_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code_token')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.String(length=10), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('annee_academique', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=10), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('salle_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('tolerance_retard_minutes', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('motif_changement', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suivi_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('nombre_absences', sa.Integer(), nullable=True),
    sa.Column('nb_absences_justifiees', sa.Integer(), nullable=True),
    sa.Column('seuil_atteint', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etudiant_id', 'matiere_id', name='uq_etudiant_matiere')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['destinataire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_pointage', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('methode', sa.String(length=20), nullable=True),
    sa.Column('wifi_detecte', sa.Boolean(), nullable=True),
    sa.Column('qr_valide', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accorde_par', sa.Integer(), nullable=True),
    sa.Column('justificatif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accorde_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['etudiant_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pointages', schema=None) as batch_op:
        batch_op.create_index('uq_pointage_etudiant_cours_valide', ['etudiant_id', 'cours_id'], unique=True, postgresql_where=sa.text("statut IN ('present', 'retard')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pointages', schema=None) as batch_op:
        batch_op.drop_index('uq_pointage_etudiant_cours_valide', postgresql_where=sa.text("statut IN ('present', 'retard')"))

    op.drop_table('pointages')
    op.drop_table('notifications')
    op.drop_table('suivi_absences')
    op.drop_table('cours')
    op.drop_table('utilisateurs')
    op.drop_table('promotions')
    op.drop_table('salles')
    op.drop_table('parametres')
    op.drop_table('matieres')
    op.drop_table('filieres')
    # ### end Alembic commands ###
