from app.models.filiere import Filiere
from app.models.promotion import Promotion
from app.models.utilisateur import Utilisateur
from app.models.matiere import Matiere
from app.models.salle import Salle
from app.models.cours import Cours
from app.models.pointage import Pointage
from app.models.suivi_absences import SuiviAbsences
from app.models.notification import Notification
from app.models.parametre import Parametre
